### PR TITLE
Conf upgrade + remove console.log

### PR DESCRIPTION
**Pull request by Yarflam**
To correct errors of my issue:
https://github.com/revolunet/node-sellsy/issues/10

Thanks ;)

### CODE REVIEW

**Comment by Yarflam** [comment]
Can no one verify and merge? Thank you

**Comment by elieteyssedou** [comment]
+1 for removing the console.log

@revolunet please, can you check this MR ? 🙏🏻 Thanks a lot :)

**Comment by Yarflam** [comment]
(the reason for my force-push: I corrected my pseudo/email)

I see 4 collaborators in this repository, @revolunet @nfroidure @risseraka @yereby ; I don't want to create another NPM package for this. I'll add my GIT repository for now. Thank you :D

**Comment by revolunet** [comment]
Hi, sorry for the delay, i'll take a look in the next week, thanks for helping here

**Comment by revolunet** [comment]
Hi, i made some more changes in #12, had some issues with eslint, can you please check if ok for you ?

Thanks

**Comment by Yarflam** [comment]
Hi, thanks for reviewing the code! No problem with your eslint setting.

Just a few warnings detected, nothing more:

```bash
/src/Documents.js
   51:15  warning  'e' is defined but never used  no-unused-vars
   71:15  warning  'e' is defined but never used  no-unused-vars
   88:15  warning  'e' is defined but never used  no-unused-vars
  114:15  warning  'e' is defined but never used  no-unused-vars
```

It's good you deleted the `/dist` directory, I didn't dare to correct it so as not to disturb your deployment procedures.

**Comment by revolunet** [comment]
merged in #12 and released in 1.5.4 , thanks @Yarflam

**Pull request closed without merging**
